### ISSUE TITLE
File is not an image

### ISSUE THREAD

**Issue by sergiopellegrini** [achingbrain/mongoose-crate-gm#1]
Good Day, Having an issue with crate not working with images uploaded with angular-file-uploader using multiparty middleware on node. Output shown below. I have now used a few uploaders and all result in the same error.

Error: File was not an image

Your help will be greatly appreciated.

Mongoose Schema

``` javascript
directorySchema.plugin(crate,{
  storage: new S3({
    key: '***',
    secret: '***',
    bucket: 'tpbdirectory',
    acl: false, // defaults to public-read
    region: 'us-standard', // defaults to 
    path: function(attachment) { // where the file is stored in the bucket - defaults to this function
      return '/' + path.basename(attachment.path)
    }
  }),
  fields: {
    attachments: {
      array: true,
      processor: new ImageMagick({
        tmpDir: '/tmps', // Where transformed files are placed before storage, defaults to os.tmpdir()
        formats: ['JPEG', 'GIF', 'PNG'], // Supported formats, defaults to ['JPEG', 'GIF', 'PNG', 'TIFF']
        transforms: {
          original: {
            // keep the original file
          },
          small: {
            crop: '150x150',
            format: '.jpg',
            '$format':'jpg'
          },
          medium: {
            resize: '250x250',
            format: '.jpg'
          },
          slider: {
            resize: '762x461',
            format: '.jpg'
          }
        }
      })
    }
  }
});
```

Output

``` javascript
{ fieldName: 'file',
  originalFilename: 'Screen Shot 2015-04-15 at 11.08.51 AM.png',
  path: '/var/folders/p5/4plyyg4s4_v6t49xvp1v4jlc0000gn/T/2265-bjgpop.png',
  headers: 
   { 'content-disposition': 'form-data; name="file"; filename="Screen Shot 2015-04-15 at 11.08.51 AM.png"',
     'content-type': 'image/png' },
  ws: 
   { _writableState: 
      { highWaterMark: 16384,
        objectMode: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [],
        errorEmitted: false },
     writable: true,
     domain: null,
     _events: { error: [Object], close: [Object] },
     _maxListeners: 10,
     path: '/var/folders/p5/4plyyg4s4_v6t49xvp1v4jlc0000gn/T/2265-bjgpop.png',
     fd: null,
     flags: 'w',
     mode: 438,
     start: undefined,
     pos: undefined,
     bytesWritten: 436912,
     closed: true },
  size: 436912,
  name: 'Screen Shot 2015-04-15 at 11.08.51 AM.png',
  type: 'image/png' }
Screen Shot 2015-04-15 at 11.08.51 AM.png
/var/folders/p5/4plyyg4s4_v6t49xvp1v4jlc0000gn/T/2265-bjgpop.png
<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 04 f7 00 00 01 25 08 06 00 00 00 88 d4 07 41 00 00 18 22 69 43 43 50 49 43 43 20 50 72 6f 66 69 6c ...>
Error: File was not an image
    at null.<anonymous> (/Users/sergiopellegrini/Sites/advertisers/node_modules/mongoose-crate-gm/lib/ImageMagick.js:65:25)
    at gm.emit (events.js:106:17)
    at gm.<anonymous> (/Users/sergiopellegrini/Sites/advertisers/node_modules/mongoose-crate-gm/node_modules/gm/lib/getters.js:129:14)
    at ChildProcess.cb (/Users/sergiopellegrini/Sites/advertisers/node_modules/mongoose-crate-gm/node_modules/gm/lib/command.js:301:16)
    at ChildProcess.emit (events.js:95:17)
```

**Comment by achingbrain** [comment]
I've updated your issue to remove your S3 bucket secret and key, you might want to regenerate them as this is viewable by anyone.

What version of GraphicsMagick do you have installed?

**Comment by sergiopellegrini** [comment]
Thanks for the update.

I have 1.0.0 installed and updated the dependancy. Still get the following error:

Error: File was not an image
    at null.<anonymous> (/Users/sergiopellegrini/Sites/advertisers/node_modules/mongoose-crate-gm/lib/ImageMagick.js:65:25)
    at gm.emit (events.js:106:17)
    at gm.<anonymous> (/Users/sergiopellegrini/Sites/advertisers/node_modules/mongoose-crate-gm/node_modules/gm/lib/getters.js:129:14)
    at ChildProcess.cb (/Users/sergiopellegrini/Sites/advertisers/node_modules/mongoose-crate-gm/node_modules/gm/lib/command.js:301:16)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:808:12)
POST /api/upload/55252243fc49d4a4e9381713 500 191.765 ms - 660

**Comment by achingbrain** [comment]
No, I mean what version of the GraphicsMagic binary do you have installed?

When you run `gm` on the command line without any arguments, what version number is printed?

**Comment by sergiopellegrini** [comment]
Update gm and all works now thanks for the help.
